### ISSUE TITLE
Need some help troubleshooting an error I'm getting when using the toolkit.

### ISSUE THREAD

**Issue by Telarian** [developerforce/Force.com-Toolkit-for-NET#122]
I'm getting the following error when using the toolkit:
```
Newtonsoft.Json.JsonSerializationException occurred
  HResult=-2146233088
  Message=Error converting value "/services/data/v32.0/sobjects/Listing__c/a0co0000006tzdMAAQ" to type 'Salesforce.Common.Models.ErrorResponse'.
```

I'm not real sure why it would be trying to convert that string to an error response, so I'm not sure where to begin troubleshooting.

The code that's throwing the error is pretty simple:
```
Await client.UpsertExternalAsync("Listing__c", "OPAS_Combo_Listing_Id__c", String.Format("LL-{0}", ll.Id.ToString()), t)
```

t is a simple expando object that has been filled out to match the salesforce object we are upserting.
The upsert seems to have been completed. Everything seems to have worked except that it's throwing this error.

I've been using this code for some time with no problems. This just came up suddenly. So, I was thinking maybe something was funny about this particular data to cause the problem, but it seems pretty standard.

I have the full error data here:
```
Newtonsoft.Json.JsonSerializationException occurred
  HResult=-2146233088
  Message=Error converting value "/services/data/v32.0/sobjects/Listing__c/a0co0000006tzdMAAQ" to type 'Salesforce.Common.Models.ErrorResponse'. Path '[0]', line 1, position 62.
  Source=Newtonsoft.Json
  StackTrace:
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
       at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
       at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
       at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
       at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
       at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
       at Salesforce.Common.ServiceHttpClient.<HttpPatchAsync>d__36.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
       at Sylvester.Main_Form.VB$StateMachine_1_TransmitLeadsToSalesForce.MoveNext() in C:\Users\ToryN\Documents\Visual Studio 2013\Projects\Distro\Sylvester\Main_Form.vb:line 890
  InnerException: System.ArgumentException
       HResult=-2147024809
       Message=Could not cast or convert from System.String to Salesforce.Common.Models.ErrorResponse.
       Source=Newtonsoft.Json
       StackTrace:
            at Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)
            at Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(Object initialValue, CultureInfo culture, Type targetType)
            at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
       InnerException: 
```

Any assistance would be greatly appreciated.

**Comment by wadewegner** [comment]
Can you use Fiddler and capture a trace to share?

**Comment by wadewegner** [comment]
I'm going to close. If this is still a problem, please feel free to re-open. Thanks!

**Comment by Telarian** [comment]
Thank you Wade. I thought I had already closed this. Sorry to have left it open on you.

**Comment by blandoe** [comment]
Reproducible - have the ExternalId pointing to two records.  Fiddler shows the TextView return from webservice call as the below.  To be clear, Fiddler's JSON view correctly shows it as two nodes.

77
["/services/data/v32.0/sobjects/Account/xxxxxxxxxxxxxxxxxx","/services/data/v32.0/sobjects/Account/xxxxxxxxxxxxxxxxxx"]
0

**Comment by vgrabchenko** [comment]
Hello.
We're having the same issue from time to time on updates and not really able to find the root cause.
Was this resolved or it wasn't the toolkit issue? We on v 0.4.6 of the toolkit.

```
Type : Newtonsoft.Json.JsonSerializationException, Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
Message : Error converting value "/services/data/v29.0/sobjects/Contact/XXXXXXXXXXXXX" to type 'Salesforce.Common.Models.ErrorResponse'. Path '[0]', line 1, position 59.
```
`Type : System.ArgumentException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
        Message : Could not cast or convert from System.String to Salesforce.Common.Models.ErrorResponse.
        Source : Newtonsoft.Json
        Help link :
        ParamName :
        Data : System.Collections.ListDictionaryInternal
        TargetSite : System.Object EnsureTypeAssignable(System.Object, System.Type, System.Type)
        HResult : -2147024809
        Stack Trace :    at Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)
           at Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(Object initialValue, CultureInfo culture, Type targetType)
           at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)`

Thanks, Vitaliy.

**Comment by v-sefedo** [comment]
That's reproducible for me as well. Here is the stack trace:
```
Salesforce failed to complete task.
Response code: BadGateway,
Error: UnhandledExceptionInForceClient,
Message: Error converting value "/services/data/v34.0/sobjects/Case/5001e000001iMeZAAU" to type 'Salesforce.Common.Models.ErrorResponse'. Path '[0]', line 1, position 56., Source: Newtonsoft.Json.

Error Stack Trace: at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
at Salesforce.Common.ServiceHttpClient.<HttpPatchAsync>d__3a.MoveNext()
```
