### ISSUE TITLE
The REST API is not enabled for this Organization.

### ISSUE THREAD

**Issue by BharatBhatiaDev** [developerforce/Force.com-Toolkit-for-NET#142]
While creating new object with the specified steps in getting this error .
Sample: 
 var account = new Account() { Name = "New Account", Description = "New Account Description" };
                var id = await client.CreateAsync("Account", account);

error : The REST API is not enabled for this Organization.

   at Salesforce.Common.ServiceHttpClient.<HttpPostAsync>d__12`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Salesforce.Force.ForceClient.<CreateAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SalesForce.Controllers.HomeController.<Index>d__0.MoveNext() in c:\Users\bharat.bhatia\Documents\Visual Studio 2013\Projects\SalesForce\SalesForce\Controllers\HomeController.cs:line 41

**Comment by wadewegner** [comment]
There is nothing I can do to help you. You'll have to contact Salesforce and have them enable API access for your organization.
