### ISSUE TITLE
Unable to login from WCF Services

### ISSUE THREAD

**Issue by c4less** [developerforce/Force.com-Toolkit-for-NET#143]
Hi Wade,

I created a WCF Service to collect data from salesforce. I am unable to retrieve data now. It shows the below mentioned exception.

![image](https://cloud.githubusercontent.com/assets/4557657/9831934/39916afc-5988-11e5-81db-de07f949d319.png)

System.AggregateException was unhandled by user code
  HResult=-2146233088
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
       at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
       at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
       at System.Threading.Tasks.Task.Wait()
       at SalesForce.RestService.Repository.SalesforceRepository.GetAllAccounts() in h:\C#\SalesforceRestTest\SalesForce.RestService\Repository\SalesforceRepository.cs:line 43
       at SalesForce.RestService.SalesforceService.GetAllAccounts() in h:\C#\SalesforceRestTest\SalesForce.RestService\SalesforceService.svc.cs:line 26
       at SyncInvokeGetAllAccounts(Object , Object[] , Object[] )
       at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
       at System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc& rpc)
  InnerException: Salesforce.Common.ForceAuthException
       HResult=-2146233088
       Message=authentication failure
       Source=Salesforce.Common
       StackTrace:
            at Salesforce.Common.AuthenticationClient.<UsernamePasswordAsync>d__1.MoveNext()
       InnerException:

**Comment by logiticks-github** [comment]
Facing similar issue . Any solution for this ?  
"authentication failure"

   at Salesforce.Common.AuthenticationClient.<WebServerAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at pluginSalesforce.Services.SalesforceIntegration.<GetAuthToken>d__0.MoveNext()

**Comment by wadewegner** [comment]
Can you use Fiddler and capture a trace so we can see the exact error message?

**Comment by wadewegner** [comment]
Closing given the lack of additional details.
