### ISSUE TITLE
Compound Address Field - Lat/Long

### ISSUE THREAD

**Issue by sheibeck** [developerforce/Force.com-Toolkit-for-NET#183]
I'm running into an issue with GeoLocation fields when running a ForceClient.SelectEntities.

Here is the code I'm running - where "Dealer_Geocode__Longitude__s" is one field from a compound object. 

```
EntityModel model = client.DescribeEntity("Account");
client.SelectEntities("SELECT Id, Name, Dealer_Geocode__Longitude__s FROM Account", model);
```

I've verified the field exists in the model, but I get the error "Input string was not in a correct format." with the following stack trace, it looks like it's bombing out on the ParseDouble ...

```
at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Xml.XmlConvert.ToDouble(String s)
   at CMS.SalesForce.EntityDoubleAttributeModel.DeserializeValue(String value)
   at CMS.SalesForce.EntitySerializer.Deserialize(sObject entitySource, EntityModel entityModel)
   at CMS.SalesForce.SelectEntitiesResult.<>c__DisplayClass3.<.ctor>b__0(sObject x)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at CMS.SalesForce.SelectEntitiesResult..ctor(QueryResult source, EntityModel model)
   at CMS.SalesForce.SelectEntitiesCommand.Execute(String statement, EntityModel model, SalesForceClientOptions options)
   at CMS.SalesForce.SalesForceClient.SelectEntities(String statement, EntityModel model, SalesForceClientOptions options)
   at CMS.SalesForce.SalesForceClient.SelectEntities(String statement, EntityModel model)
   at HWLSalesforce.SyncDealerAccounts(TaskInfo ti) in c:\Projects\client\kentico-hwl\CMS\App_Code\CMS\HWLSalesForce.cs:line 69
   at SalesforceSyncDealerTask.Execute(TaskInfo ti) in c:\Projects\client\kentico-hwl\CMS\App_Code\_framework
```

**Comment by sheibeck** [comment]
Ah, sorry to muddy the issues list here. I see what's happening.
