### ISSUE TITLE
Login using WebServerOAuthFlow failed

### ISSUE THREAD

**Issue by imnxllet** [developerforce/Force.com-Toolkit-for-NET#206]
When I run the project, and click login, I got this

`<Error>
<Message>An error has occurred.</Message>

<ExceptionMessage>Unexpected character encountered while parsing value: <. Path '', line 0, position 0.</ExceptionMessage>

<ExceptionType>Newtonsoft.Json.JsonReaderException</ExceptionType>

<StackTrace>   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at Salesforce.Common.AuthenticationClient.<WebServerAsync>d__28.MoveNext() in C:\Users\ZhenYong.Lu\workspace\A4\Force.com-Toolkit-for-NET-master\src\CommonLibrariesForNET\AuthenticationClient.cs:line 132
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at WebServerOAuthFlow.Web.Controllers.CallbackController.<Get>d__4.MoveNext() in C:\Users\ZhenYong.Lu\workspace\A4\Force.com-Toolkit-for-NET-master\samples\WebServerOAuthFlow\WebServerOAuthFlow.Web\Controllers\CallbackController.cs:line 24
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()</StackTrace></Error>`

**Comment by CraigStuntz** [comment]
Your login failed, and the Toolkit is attempting to parse the HTML returned by the token request endpoint as JSON. Look at the request in Fiddler for more information. You'll probably see an internal error which *might* mean you need to whitelist your IP in Salesforce.

**Comment by CraigStuntz** [comment]
To be clear, since similar issues have been repeatedly closed here: This is a bug in the toolkit. You can work around it by changing your request to not get an authentication error from SF, but the toolkit ought not to attempt to parse HTML as JSON.

**Comment by wadewegner** [comment]
Totally agree, @CraigStuntz. Recently tried to fix this bug here: https://github.com/developerforce/Force.com-Toolkit-for-NET/commit/b01650f91897081deef04cba31d16cab09ef2c7a. Do we have a repro that I can use to fix any further issue here?

**Comment by CraigStuntz** [comment]
@wadewagner I can consistently reproduce the exception if I don't use TLS 1.2 (i.e., use SSL v3, which isn't supported) and then request a token from Salesforce. This produces an internal error (500) HTML response, which the Force Toolkit attempts to parse as JSON (same stack trace as original issue reported above.

**Comment by CraigStuntz** [comment]
@wadewegner Reviewing that commit, I see a couple areas for improvement. Simply rethrowing a new exception with the same message isn't going to make developers any less confused. People will continue to make duplicate reports here. 

One thing which might make sense is to detect if TLS or SSL is in use and add a specific message if appropriate. 

Another thing which would make sense is to use the content type header to determine whether to parse as JSON (presuming Salesforce sets it; this seems likely, but I'm not at my desk to check). 

Ideally, if an exception must be thrown it would contain the body of the response instead of a parsing error.

**Comment by wadewegner** [comment]
Good feedback. I'll work on it. In particular, thanks for the idea around TLS 1.2 -- definitely something I too can reproduce.

**Comment by CraigStuntz** [comment]
One other code change I think might help is to change all the demo projects in [this folder](https://github.com/developerforce/Force.com-Toolkit-for-NET/tree/master/samples) to use TLS 1.2, as lots of people probably follow those examples.

**Comment by wadewegner** [comment]
If this is still an issue (see latest updates to code) please re-open with more specifics.
