### ISSUE TITLE
ParseForceException: unable to convert from System.String to Salesforce.Common.Models.Json.ErrorResponse

### ISSUE THREAD

**Issue by duckwizzle** [developerforce/Force.com-Toolkit-for-NET#315]
ParseForceException is failing to deserialize the string listed below into an `ErrorResponses` class.

`["/services/data/v41.0/sobjects/Account/0011I00000aCPEAQA4","/services/data/v41.0/sobjects/Account/0011I00000aAsbRQAS"]`

Message:

`Error converting value "/services/data/v41.0/sobjects/Account/0011I00000aCPEAQA4" to type 'Salesforce.Common.Models.Json.ErrorResponse'. Path '[0]', line 1, position 59.`

Inner exception:

`Could not cast or convert from System.String to Salesforce.Common.Models.Json.ErrorResponse.`

StackTrace:

`   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at Salesforce.Common.JsonHttpClient.ParseForceException(String responseMessage) in F:\Programming\Work Projects\Epona\ForceCommonLibrariesForNET\JsonHttpClient.cs:line 29
   at Salesforce.Common.JsonHttpClient.<HttpPatchAsync>d__12.MoveNext() in F:\Programming\Work Projects\Epona\ForceCommonLibrariesForNET\JsonHttpClient.cs:line 204
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Salesforce.Common.JsonHttpClient.<HttpPatchAsync>d__11.MoveNext() in F:\Programming\Work Projects\Epona\ForceCommonLibrariesForNET\JsonHttpClient.cs:line 181`

**Comment by v-sefedo** [comment]
That's reproducible for me as well. Here is the stack trace:
```
Salesforce failed to complete task.
Response code: BadGateway,
Error: UnhandledExceptionInForceClient,
Message: Error converting value "/services/data/v34.0/sobjects/Case/5001e000001iMeZAAU" to type 'Salesforce.Common.Models.ErrorResponse'. Path '[0]', line 1, position 56., Source: Newtonsoft.Json.

Error Stack Trace: at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
at Salesforce.Common.ServiceHttpClient.<HttpPatchAsync>d__3a.MoveNext()
```
