### ISSUE TITLE
login with sales force

### ISSUE THREAD

**Issue by JayasreeR** [developerforce/Force.com-Toolkit-for-NET#34]
Hi,
I am getting the below error while trying to login Salesforce.com through C#. Can you please help me to solve this issue.

Error:
  at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type
 objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectT
ype)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, Jso
nSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSeriali
zerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at Salesforce.Common.AuthenticationClient.<UsernamePasswordAsync>d__7.MoveNex
t()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()

**Comment by imnxllet** [comment]
Hi, I am having the same issue too. 
`<Error><Message>An error has occurred.</Message><ExceptionMessage>Unexpected character encountered while parsing value: <. Path '', line 0, position 0.</ExceptionMessage><ExceptionType>Newtonsoft.Json.JsonReaderException</ExceptionType><StackTrace>   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at Salesforce.Common.AuthenticationClient.<WebServerAsync>d__28.MoveNext() in C:\Users\ZhenYong.Lu\workspace\A4\Force.com-Toolkit-for-NET-master\src\CommonLibrariesForNET\AuthenticationClient.cs:line 132
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at WebServerOAuthFlow.Web.Controllers.CallbackController.<Get>d__4.MoveNext() in C:\Users\ZhenYong.Lu\workspace\A4\Force.com-Toolkit-for-NET-master\samples\WebServerOAuthFlow\WebServerOAuthFlow.Web\Controllers\CallbackController.cs:line 24
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()</StackTrace></Error>`

**Comment by wadewegner** [comment]
A fix recently went in to handle this better. However, underlying it is an authentication error. Use a tool like Fiddler to look at the trace to see what's happening and share the results please.

**Comment by imnxllet** [comment]
ok thanks, I will try

**Comment by imnxllet** [comment]
And also, when I try to run the SimpleConsole project, looks like I can't get through,

`Authenticating with Salesforce
One or more errors occurred.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceled
Exceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationTo
ken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at SimpleConsole.Program.Main() in C:\Users\ZhenYong.Lu\workspace\A4\Force.co
m-Toolkit-for-NET-master\samples\SimpleConsole\Program.cs:line 26
retry your request
   at Salesforce.Common.AuthenticationClient.<UsernamePasswordAsync>d__1.MoveNex
t()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at SimpleConsole.Program.<RunSample>d__7.MoveNext() in C:\Users\ZhenYong.Lu\w
orkspace\A4\Force.com-Toolkit-for-NET-master\samples\SimpleConsole\Program.cs:li
ne 59`

**Comment by imnxllet** [comment]
Do you know what can be causing this, I already provided the corrent info(consumer key, secret, username....) in the app.config

**Comment by wadewegner** [comment]
No, I don't know what's causing this. You need to debug. Easiest way is to capture an HTTP trace and look at the exact message coming from Salesforce.

**Comment by relick89** [comment]
Hello, I am having the same issue . It works fine on visual studio 2015 and iisexpress but when i deploy it on my server with windows server 2008 and iis 7.5 this error came out. 

[JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.]
   Newtonsoft.Json.JsonTextReader.ParseValue() +1317
   Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter) +104
   Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent) +750
   Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType) +281
   Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings) +168
   Newtonsoft.Json.JsonConvert.DeserializeObject(String value, JsonSerializerSettings settings) +61
   Salesforce.Common.<WebServerAsync>d__a.MoveNext() +3219
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13847892
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   SalesforceWebApplication.Salesforce.<AcquireTokenByAuthorizationCodeAsync>d__2.MoveNext() +391
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13847892
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   SalesforceWebApplication.Salesforce.<ProcessRequestAsync>d__2.MoveNext() +248
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13847892
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   System.Web.TaskAsyncHelper.EndTask(IAsyncResult ar) +69
   System.Web.CallHandlerExecutionStep.OnAsyncHandlerCompletion(IAsyncResult ar) +178

**Comment by imnxllet** [comment]
Not sure if this helps, but put this line before the authentication:
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

**Comment by relick89** [comment]
where exactly? im using oauth login.

**Comment by imnxllet** [comment]
anywhere before creating the oauth i guess

**Comment by relick89** [comment]
nothing :( . why it works fine on iisexpress and after deploy come out this thing? it's really boring.

**Comment by joaopaulonobrega** [comment]
@imnxllet 
tnks man , you saved me, my error with sendbox:

`<ExceptionMessage>Unexpected character encountered while parsing value: e. Path '', line 0, position 0.</ExceptionMessage>`

solution : ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 before UsernamePasswordAsync method in AuthenticationClient class.

Tnks

**Comment by relick89** [comment]
Thks solved today. Was a typo errore.

Il 02/set/2016 04:20 PM, "joaopaulonobrega" <notifications@github.com> ha
scritto:

**Comment by sjones538comcast** [comment]
Hi All,
There are a few things that may cause Salesforce API integration login errors like "authentication failure" and "nexpected character encountered while parsing value: e. Path...". Here is check list to ensure a guaranteed solution:
1. Make sure you are passing the token URL into the AuthenticationClient.UsernamePasswordAsync if you are appending an security token with your password.
2. Make sure your token URL is pointing to the sandbox URL "https://test.salesforce.com/services/oauth2/token" or the product URL "https://login.salesforce.com/services/oauth2/token" if you are accessing a production environment.
3. Make sure you are using the correct security token, client id, and client secret as well as username and password credentials.
4. Make sure you assign the correct security protocol to ServicePointManager.SecurityProtocol. (i.e. SecurityProtocolType.Tls11). This needs to be set before you attempt to login.

Hope this helps.

Thanks,
Sidney

**Comment by AhmadiRamin** [comment]
I've done everything mentioned here but still getting the authentication failure error, here is my code:

`   var auth = new AuthenticationClient();
                ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
                await auth.UsernamePasswordAsync(sfclientId, sfclientSecret, userName, password, "https://login.salesforce.com/services/oauth2/token");

                var client = new ForceClient(auth.InstanceUrl, auth.AccessToken, auth.ApiVersion);
                var accounts = await client.QueryAsync<Account>("SELECT id, name, description FROM Account");

                foreach (var account in accounts.Records)
                {
                    Console.WriteLine(account.Name);
                }

`

I'm using a console application, not sure if it doesn't work with this project type.
Also checked IP Relaxation, everything seems fine!

**Comment by elmz87** [comment]
> I've done everything mentioned here but still getting the authentication failure error, here is my code:
> 
> ` var auth = new AuthenticationClient();
> ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
> await auth.UsernamePasswordAsync(sfclientId, sfclientSecret, userName, password, "https://login.salesforce.com/services/oauth2/token");
> 
> ```
>             var client = new ForceClient(auth.InstanceUrl, auth.AccessToken, auth.ApiVersion);
>             var accounts = await client.QueryAsync<Account>("SELECT id, name, description FROM Account");
> 
>             foreach (var account in accounts.Records)
>             {
>                 Console.WriteLine(account.Name);
>             }
> ```
> 
> `
> 
> I'm using a console application, not sure if it doesn't work with this project type.
> Also checked IP Relaxation, everything seems fine!

I am getting the same error time to time too
