### ISSUE TITLE
Unable to read data from the transport connection: A connection attempt failed because the connected party

### ISSUE THREAD

**Issue by faiyaz458** [developerforce/Force.com-Toolkit-for-NET#416]
When I call below function locally form my dev machine, it executed successfully and without any issues. Getting issue only on UAT and production server. I have also checked that TLS1.2 is enabled on servers. Please suggest.

**await auth.UsernamePasswordAsync(_ConsumerKey, _ConsumerSecret, _Username, _Password + _SecurityToken, url);**

Error: 
CoreCLR Version: 4.700.20.41105

.NET Core Version: 3.1.8

Description: The process was terminated due to an unhandled exception.

Exception Info: System.AggregateException: One or more errors occurred. (The SSL connection could not be established, see inner exception.)

---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.

---> System.IO.IOException: Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond..

---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

   --- End of inner exception stack trace ---

   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)

   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)

   at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)

   at System.Net.Security.SslStream.ThrowIfExceptional()

   at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)

   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)

   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)

   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__65_1(IAsyncResult iar)

   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)

--- End of stack trace from previous location where exception was thrown ---

   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)

   --- End of inner exception stack trace ---

   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)

   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)

   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)

   at Salesforce.Common.AuthenticationClient.UsernamePasswordAsync(String clientId, String clientSecret, String username, String password, String tokenRequestEndpointUrl)

   at SalesforceClient.SalesforceLoginAsync() in N:\Worldwide\Analytics\BAU\Weekly_Reports\Salesforce-to-SQL-Server-Kimble\SalesforceClient.cs:line 47

   at SalesforceClient.CreateClientAsync() in N:\Worldwide\Analytics\BAU\Weekly_Reports\Salesforce-to-SQL-Server-Kimble\SalesforceClient.cs:line 69

   --- End of inner exception stack trace ---

   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)

   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)

   at System.Threading.Tasks.Task.Wait()

**Comment by faiyaz458** [comment]
I resolved this issue by whitelisting the URLs on server. 
Thanks
