### ISSUE TITLE
Unable to login into salesforce with Console Application

### ISSUE THREAD

**Issue by c4less** [developerforce/Force.com-Toolkit-for-NET#56]
![image](https://cloud.githubusercontent.com/assets/4557657/4281265/eaaa128e-3d3d-11e4-861b-bb333ddad6af.png)

System.AggregateException was caught
  HResult=-2146233088
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
       at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
       at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
       at System.Threading.Tasks.Task.Wait()
       at SalesforceApplication.Program.Main() in h:\ASP.net\SalesforceApplication\SalesforceApplication\Program.cs:line 29
  InnerException: System.NullReferenceException
       HResult=-2147467261
       Message=Object reference not set to an instance of an object.
       Source=SalesforceApplication
       StackTrace:
            at SalesforceApplication.Program.<RunSample>d__1c.MoveNext() in h:\ASP.net\SalesforceApplication\SalesforceApplication\Program.cs:line 53
       InnerException: 

Its showing above mentioned exception. Kindly help me on this

**Comment by WiseLinProject** [comment]
The keypoint is the fuction Wait(); of auth.UsernamePasswordAsync(_clientId, _clientSecret, _username, _password).Wait();

I really found the answer from this article, thank you!
https://github.com/wadewegner/TechEd14SDK/blob/master/src/ConsoleApplication1/Program.cs#L19
