### ISSUE TITLE
Parsing error when refresh token

### ISSUE THREAD

**Issue by happytrails** [developerforce/Force.com-Toolkit-for-NET#85]
On build 0.6.4, get the following error when calling ForceClient.UserInfo.
Error message: Unexpected character encountered while parsing value: e. Path '', line 0, position 0.

Stack trace: 
at Newtonsoft.Json.JsonTextReader.ParseValue()
at Newtonsoft.Json.JsonTextReader.ReadInternal()
at Newtonsoft.Json.JsonTextReader.Read()
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
at Newtonsoft.Json.JsonConvert.DeserializeObjectT
at Newtonsoft.Json.JsonConvert.DeserializeObjectT
at Salesforce.Common.ServiceHttpClient.d__161.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter1.GetResult()
at Salesforce.Force.ForceClient.d__b1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter1.GetResult() ...

Did a little debugging, the error is thrown from ServiceHttpClient.cs / HttpGetAsync function by this line of code:

            var errorResponse = JsonConvert.DeserializeObject<ErrorResponses>(response);

The root issue is that the error handling code assumes response object is a JSON string, but it's actually just a simple string "Bad_OAuth_Token".

**Comment by wadewegner** [comment]
Here's a test I've put together to try and reproduce. Seems to work properly. Commit: https://github.com/developerforce/Force.com-Toolkit-for-NET/commit/d243a5df30c268e88fd506577f77ef6a03f01921

Does this test cover your scenario?

Note: The following `UserInfo` unit test has existed for quite awhile and currently runs as expected: https://github.com/developerforce/Force.com-Toolkit-for-NET/blob/master/src/ForceToolkitForNet.FunctionalTests/ForceClientTests.cs#L50

**Comment by juan-cs** [comment]
I was able to reproduce it as described: calling `ForceClient.UserInfo` with a bad token throws an exception because the code assumes a JSON response and the API returns `Bad_OAuth_Token`.

This is how to reproduce the issue:
```
_auth = new AuthenticationClient();
_auth.UsernamePasswordAsync(ConsumerKey, ConsumerSecret, Username, Password, TokenRequestEndpointUrl).Wait();

var badToken = "badtoken";
var client = new ForceClient(_authentication.InstanceUrl, badToken, _authentication.ApiVersion);

try
{
    await client.UserInfo<UserInfo>(_auth .Id);
}
catch (ForceException ex)
{
    Assert.IsNotNull(ex);
    Assert.IsNotNull(ex.Message);
    Assert.That(ex.Message, Is.EqualTo("Session expired or invalid"));
    Assert.IsNotNull(ex.Error);
}
```
