### ISSUE TITLE
JSON parse error on long queries with QueryAsync

### ISSUE THREAD

**Issue by Prooskalia** [developerforce/Force.com-Toolkit-for-NET#88]
In a long query (in my case, a large number of values in an IN criterion in the WHERE clause), the call to QueryAsync gives a JSON parse error.  In my test case the same ID (i.e. 001E0000014Zpov) was duplicated a number of times with comma separators and single-quote delimiters and included in the statement:

                             SELECT Id FROM Account WHERE Id IN (                  )

With 887 instances of the ID the call succeeded but with 888 instances it failed with:

      "Unexpected character encountered while parsing value: E. Path '', line 0, position 0."

The query string was only 16,020 characters (smaller than the maximum of 20,000 I've seen mentioned elsewhere) ... adding in whitespace and re-running finds the maximum size allowed appears to be 16,007.  Hardly a major concern as, knowing this, one can hard-code a maximum size of, say, 16,000 but the error message appears misleading.

But then I noticed that if the QueryAsync() is called twice on a long query-string, the first call succeeds but the second call fails with that same exception.  To repeat:

        [Serializable] private class Account { public string Id { get; set; } }

        var queryString = string.Format("SELECT Id FROM Account WHERE Id IN ({0})",
            string.Join(",", Enumerable.Range(1, 887).Select(i => "'X01E0000014Zpov'")));

        Debug.Print(queryString.Length.ToString()); // 16002
        var response1 = await client.QueryAsync<Account>(queryString);
        Debug.Print("After first query");
        var response2 = await client.QueryAsync<Account>(queryString);
        Debug.Print("After second query");

Gives output:

        16002
        After first query
        A first chance exception of type 'Newtonsoft.Json.JsonReaderException' occurred in mscorlib.dll

Best Regards.

Stacktrace:
--------------
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.ReadInternal()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at Salesforce.Common.ServiceHttpClient.<HttpGetAsync>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TestSfDownload.Form1.<ProoGet>d__12.MoveNext() in c:\Users\prooskalia\Desktop\TestSfDownload\TestSfDownload\Form1.cs:line 114

**Comment by wadewegner** [comment]
I just tried creating a quick test for this ...

``` c#
[Test]
public async void Test()
{
    var queryString = string.Format("SELECT Id FROM Account WHERE Id IN ({0})",
        string.Join(",", Enumerable.Range(1, 887).Select(i => "'X01E0000014Zpov'")));
            
    var response1 = await _client.QueryAsync<Account>(queryString);
    Assert.IsNotNull(response1);

    var response2 = await _client.QueryAsync<Account>(queryString);
    Assert.IsNotNull(response2);
}
```

... and in Fiddler see the following error back from the API:

```
HTTP/1.1 413 Request Entity Too Large: head
Connection: close

Error: Request Entity Too Large: head
```

Can you clarify or, better yet, share a code snippet that works in a clean Developer's Org? If necessary, write a method to create all 887 records ahead of time so we have a good test.

Thank you!

**Comment by wadewegner** [comment]
If this is still an issue, please re-open with a repro. Thanks!
